M48
; DRILL file {KiCad 7.0.2} date Sat 22 Apr 2023 08:19:11 PM -03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-22T20:19:11-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X6.1417Y-3.8976
X6.378Y-3.4252
X7.4803Y-3.4252
X7.7559Y-3.8976
T0
M30
